// The route table: the router, the left navigation and the end-to-end test all read this
// one list, so they cannot drift apart. It holds no JSX and loads screens lazily, so the
// end-to-end test can import it in Node.

import {
  Activity,
  BookOpenCheck,
  Bot,
  Cpu,
  FileText,
  Fingerprint,
  Gauge,
  GitFork,
  Globe,
  HeartPulse,
  Inbox,
  Landmark,
  Layers,
  type LucideIcon,
  Package,
  Plug,
  Power,
  Rocket,
  ScrollText,
  ShieldCheck,
  ShieldHalf,
  TriangleAlert,
  UserCheck,
} from 'lucide-react';
import { type ComponentType, type LazyExoticComponent, lazy } from 'react';
import { getAudit, getIntegration, getTest } from './data';

export type NavGroup = 'Overview' | 'Catalogue' | 'Runtime oversight' | 'Governance' | 'External';

export const NAV_GROUPS: NavGroup[] = [
  'Overview',
  'Catalogue',
  'Runtime oversight',
  'Governance',
  'External',
];

export interface RouteDef {
  id: string;
  path: string;
  /** The page's h1, as the end-to-end test expects it on `sample`. */
  heading: string;
  /** One line under the h1 saying what the screen is for; 140 characters or fewer. */
  purpose: string;
  /** A concrete URL for the route, with seeded IDs filled in. */
  sample: string;
  /** Shows runtime behaviour, so it carries the "Demo data" label. */
  demo: boolean;
  layout: 'console' | 'auditor' | 'trust';
  nav?: { group: NavGroup; label: string; icon: LucideIcon };
  component: LazyExoticComponent<ComponentType>;
}

const SAMPLE_TEST = 'TST-019';
const SAMPLE_INTEGRATION = 'int-mcp';
const SAMPLE_AUDIT = 'AUD-2026-01';

export const routes: RouteDef[] = [
  {
    id: 'posture',
    path: '/',
    heading: 'Posture overview',
    purpose: 'Where tests and controls stand today, and what to fix first.',
    sample: '/',
    demo: true,
    layout: 'console',
    nav: { group: 'Overview', label: 'Posture', icon: Gauge },
    component: lazy(() => import('./screens/posture')),
  },
  {
    id: 'onboarding',
    path: '/onboarding',
    heading: 'Onboarding',
    purpose:
      'Connect model calls, pick the integration depth and see which assessment route applies.',
    sample: '/onboarding',
    demo: true,
    layout: 'console',
    nav: { group: 'Overview', label: 'Onboarding', icon: Rocket },
    component: lazy(() => import('./screens/onboarding')),
  },
  {
    id: 'coverage',
    path: '/coverage',
    heading: 'Article coverage',
    purpose:
      'Which EU AI Act duties NAG checks, which it shares with you, and which need attention.',
    sample: '/coverage',
    demo: true,
    layout: 'console',
    nav: { group: 'Overview', label: 'Article coverage', icon: Landmark },
    component: lazy(() => import('./screens/coverage')),
  },
  {
    id: 'ai-systems',
    path: '/ai-systems',
    heading: 'AI systems',
    purpose: 'The AI systems in your inventory, their risk tier, your role and any open signals.',
    sample: '/ai-systems',
    demo: true,
    layout: 'console',
    nav: { group: 'Overview', label: 'AI systems', icon: Cpu },
    component: lazy(() => import('./screens/ai-systems')),
  },
  {
    id: 'tests',
    path: '/tests',
    heading: 'Tests',
    purpose: 'Automated checks that feed your controls; failing and overdue ones come first.',
    sample: '/tests',
    demo: true,
    layout: 'console',
    nav: { group: 'Catalogue', label: 'Tests', icon: Activity },
    component: lazy(() => import('./screens/tests')),
  },
  {
    id: 'test-detail',
    path: '/tests/:id',
    heading: getTest(SAMPLE_TEST)!.name,
    purpose: 'One automated check: what fails, since when, and how to fix it.',
    sample: `/tests/${SAMPLE_TEST}`,
    demo: true,
    layout: 'console',
    component: lazy(() => import('./screens/tests/detail')),
  },
  {
    id: 'controls',
    path: '/controls',
    heading: 'Controls',
    purpose: 'Controls with the tests, documents and policies that show they work.',
    sample: '/controls',
    demo: false,
    layout: 'console',
    nav: { group: 'Catalogue', label: 'Controls', icon: ShieldCheck },
    component: lazy(() => import('./screens/controls')),
  },
  {
    id: 'integrations',
    path: '/integrations',
    heading: 'Integrations',
    purpose: 'The sources NAG reads from; fix the ones in error first, then connect more.',
    sample: '/integrations',
    demo: true,
    layout: 'console',
    nav: { group: 'Catalogue', label: 'Integrations', icon: Plug },
    component: lazy(() => import('./screens/integrations')),
  },
  {
    id: 'integration-detail',
    path: '/integrations/:id',
    heading: getIntegration(SAMPLE_INTEGRATION)!.name,
    purpose: 'One source: its connection, health, scope and the tests it feeds.',
    sample: `/integrations/${SAMPLE_INTEGRATION}`,
    demo: true,
    layout: 'console',
    component: lazy(() => import('./screens/integrations/detail')),
  },
  {
    id: 'evidence',
    path: '/evidence',
    heading: 'Evidence',
    purpose:
      'Tamper-evident records of every AI request, with the last integrity check and its gaps.',
    sample: '/evidence',
    demo: true,
    layout: 'console',
    nav: { group: 'Runtime oversight', label: 'Evidence', icon: Fingerprint },
    component: lazy(() => import('./screens/evidence')),
  },
  {
    id: 'quarantine',
    path: '/quarantine',
    heading: 'Quarantine queue',
    purpose: 'Items held for a human decision; each needs a written justification.',
    sample: '/quarantine',
    demo: true,
    layout: 'console',
    nav: { group: 'Runtime oversight', label: 'Quarantine', icon: Inbox },
    component: lazy(() => import('./screens/quarantine')),
  },
  {
    id: 'kill-switch',
    path: '/kill-switch',
    heading: 'Kill switch',
    purpose: 'Stop all AI traffic at the gateway, and resume it with two approvals.',
    sample: '/kill-switch',
    demo: true,
    layout: 'console',
    nav: { group: 'Runtime oversight', label: 'Kill switch', icon: Power },
    component: lazy(() => import('./screens/kill-switch')),
  },
  {
    id: 'lineage',
    path: '/lineage',
    heading: 'Lineage',
    purpose: 'The call graph of one agent trace: who called whom and how each call ended.',
    sample: '/lineage',
    demo: true,
    layout: 'console',
    nav: { group: 'Runtime oversight', label: 'Lineage', icon: GitFork },
    component: lazy(() => import('./screens/lineage')),
  },
  {
    id: 'policy-bundles',
    path: '/policy-bundles',
    heading: 'Policy bundles',
    purpose: 'Loaded policy bundles with their class and latency budget.',
    sample: '/policy-bundles',
    demo: true,
    layout: 'console',
    nav: { group: 'Runtime oversight', label: 'Policy bundles', icon: Layers },
    component: lazy(() => import('./screens/policy-bundles')),
  },
  {
    id: 'runtime-health',
    path: '/runtime-health',
    heading: 'Runtime health',
    purpose: 'Latency budgets, breaches and what happens to requests when NAG is unreachable.',
    sample: '/runtime-health',
    demo: true,
    layout: 'console',
    nav: { group: 'Runtime oversight', label: 'Runtime health', icon: HeartPulse },
    component: lazy(() => import('./screens/runtime-health')),
  },
  {
    id: 'privacy',
    path: '/privacy',
    heading: 'Privacy and erasure',
    purpose: 'What the evidence log keeps, where content logging is on, and erasure on request.',
    sample: '/privacy',
    demo: true,
    layout: 'console',
    nav: { group: 'Runtime oversight', label: 'Privacy and erasure', icon: ShieldHalf },
    component: lazy(() => import('./screens/privacy')),
  },
  {
    id: 'packages',
    path: '/packages',
    heading: 'Conformity packages',
    purpose: 'Build the technical file for your assessment route, section by section.',
    sample: '/packages',
    demo: true,
    layout: 'console',
    nav: { group: 'Governance', label: 'Conformity packages', icon: Package },
    component: lazy(() => import('./screens/packages')),
  },
  {
    id: 'qms',
    path: '/qms',
    heading: 'QMS library',
    purpose: 'Quality management templates and their approval chain.',
    sample: '/qms',
    demo: false,
    layout: 'console',
    nav: { group: 'Governance', label: 'QMS library', icon: BookOpenCheck },
    component: lazy(() => import('./screens/qms')),
  },
  {
    id: 'documents',
    path: '/documents',
    heading: 'Documents',
    purpose: 'Compliance documents with their renewal cadence and approval status.',
    sample: '/documents',
    demo: false,
    layout: 'console',
    nav: { group: 'Governance', label: 'Documents', icon: FileText },
    component: lazy(() => import('./screens/documents')),
  },
  {
    id: 'policies',
    path: '/policies',
    heading: 'Policies',
    purpose: 'Written policies with their version, approvers and renewal date.',
    sample: '/policies',
    demo: false,
    layout: 'console',
    nav: { group: 'Governance', label: 'Policies', icon: ScrollText },
    component: lazy(() => import('./screens/policies')),
  },
  {
    id: 'risks',
    path: '/risks',
    heading: 'Risk register',
    purpose: 'Risk scenarios scored before and after treatment.',
    sample: '/risks',
    demo: false,
    layout: 'console',
    nav: { group: 'Governance', label: 'Risk register', icon: TriangleAlert },
    component: lazy(() => import('./screens/risks')),
  },
  {
    id: 'assistant',
    path: '/assistant',
    heading: 'Assistant',
    purpose: 'Ask questions about your posture; answers cite the seeded records they use.',
    sample: '/assistant',
    demo: true,
    layout: 'console',
    nav: { group: 'Governance', label: 'Assistant', icon: Bot },
    component: lazy(() => import('./screens/assistant')),
  },
  {
    id: 'auditor',
    path: '/auditor/:auditId',
    heading: getAudit(SAMPLE_AUDIT)!.name,
    purpose: 'The requests of one audit and the evidence shared for each.',
    sample: `/auditor/${SAMPLE_AUDIT}`,
    demo: false,
    layout: 'auditor',
    nav: { group: 'External', label: 'Auditor view', icon: UserCheck },
    component: lazy(() => import('./screens/auditor')),
  },
  {
    id: 'trust',
    path: '/trust',
    heading: 'Trust page',
    purpose: 'What this organisation has in place for its AI systems, kept up to date.',
    sample: '/trust',
    demo: false,
    layout: 'trust',
    nav: { group: 'External', label: 'Public trust page', icon: Globe },
    component: lazy(() => import('./screens/trust')),
  },
];
